# @format

BOT:
  OWNERS: ["271996841367830529", "908648080876920862","1031783064948453456"]
  ADMINS: ["271996841367830529","1031783064948453456"]
  TOPGG_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwODk1MDQ1Nzc3MzQzMTE5NzYiLCJib3QiOnRydWUsImlhdCI6MTcxOTkyNDMyMH0.BNyiJBJLRCs9KEXqu19DH4a8ihf51KVqrseWi6Bkr00"

LINKS:
  SUPPORT: "https://discord.com/invite/8McREhqcPB"

SPOTIFY:
  ID: "500295ff7af14eab8867381183553638"
  SECRET: "5c5696323ce54e18bffb79e02f1e8ebb"

HYDROGEN:
  PREFIX: "!"
  EMOJIS: "black"
  COLOR:  "#2f3136"
  SHARDS: "auto"
  PER_CLUSTER: 2
  TOKEN: "MTA4OTUwNDU3NzczNDMxMTk3Ng.Glh1jq.N2hwEGAKkwtgnz_Appibs6oi1sNkAv8gnTSvqU"
  TOPGGAUTH: "https://top.gg"
  VOTEURI: "https://top.gg/bot/1089504577734311976/vote"

WEBHOOKS:
  ERROR: "https://discord.com/api/webhooks/1226890375315066940/sCXhQNRf4fmjIq6HVfmRqSXWDni2wk39x2F9pj0sBaW3KZUxK0xKS3Ti7a7N26DZ6OTS"
  STATIC: "https://discord.com/api/webhooks/1226890433536458812/fK0Mcpnyik8qGYGfR0414tZX3T59FdV54qCMo0FxmWcD31c2AlTA_SX6523TwpLjWy95"
  PLAYER: "https://discord.com/api/webhooks/1226890223372472380/BHv3jFhERgiCIMQ9s30a8rSL2hUZJAd8CS11Rvdb2lA-bIHtUBkO1XJ0CIySnrbyLPvh"
  SERVER: "https://discord.com/api/webhooks/1226889954102214666/fPHiI_5iDgOsYzReuAC6nqHfaJQFBjYDWLNd5vOtjpn3VFmCfsXKgJVRhlvHl4q846VP"
  COMMAND: "https://discord.com/api/webhooks/1226889568683298846/XnEcKIZ00Vdk0yjHEXUAQ_Aiq6ikxYcWBpQwZ5lL6DKa9g_BDHYgXGkxJP6BnOdHbn8R"
